version: '3.8'

services:
    localhost:
        container_name: pg_emana
        image: 'postgres:12'
        restart: always
        expose:
            - '5433'
        ports:
            - '5433:5433'
        environment:
            POSTGRES_USER: 'emana'
            POSTGRES_PASSWORD: '12345'
            POSTGRES_DB: 'postgres'
        volumes:
            - pg_emana_data:/var/lib/postgresql/data
        command: -p 5433

volumes:
    pg_emana_data: {}
